sudo: false

before_script:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  bash -eu ./.travis/prepare_sync.sh; fi
script:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  bash -eu ./.travis/sync.sh; fi

notifications:
  email: false
